module.exports = {
  skill: [
    // skillSidebar
    'skill/skill-intro',
    {
      type: 'category',
      label: 'NodeJs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/nodejs',
        },
      ],
    },
  ]
}
